# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e9e63fd4e1ab9f77c492b9d48540c5e047f229ecd833141810e4c434f4ba66829e71eb11a501360543ea9e251e11cbd1a6b02a74455e65880387e5e9278b7fe6

test:
  secret_key_base: c06e525bb92c91ab3c8977b1172bcef4074508fc86d92626c4cbe1a980dbc6d092e97ca645942cc0bc6af399c334ec584376c7fcf71785cfcb0ee34a51353106

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
